/**
 *  WYDUSERPHOTO 스키마
 */

 CREATE TABLE WYDUSERPHOTO (
              USERID		VARCHAR2(15) PRIMARY KEY
             ,UUUIDNAME		VARCHAR2(50)  NOT NULL
             ,UFILENAME     VARCHAR2(200) NOT NULL
             ,ULOCATION		VARCHAR2(500) NOT NULL
             ,UURL			VARCHAR2(500) NOT NULL 
             ,UFILESIZE		NUMBER DEFAULT(0)
             ,UFILETYPE		VARCHAR2(200) NOT NULL
            ,CONSTRAINT WYDUSERPHOTO_USERID_FK FOREIGN KEY(USERID) REFERENCES WYDUSER(USERID) ON DELETE CASCADE
 );
  
SELECT * FROM WYDUSERPHOTO;

DROP TABLE WYDUSERPHOTO;