/**
 *  WYDPOSTPHOTO 스키마
 */

 CREATE TABLE WYDPOSTPHOTO (
              POSTID		NUMBER PRIMARY KEY
             ,PUUIDNAME		VARCHAR2(50)  NOT NULL
             ,PFILENAME     VARCHAR2(200) NOT NULL
             ,PLOCATION		VARCHAR2(500) NOT NULL
             ,PURL			VARCHAR2(500) NOT NULL 
             ,PFILESIZE		NUMBER DEFAULT(0)
             ,PFILETYPE		VARCHAR2(200) NOT NULL
            ,CONSTRAINT WYDPOSTPHOTO_POSTID_FK FOREIGN KEY(POSTID) REFERENCES WYDPOST(POSTID) ON DELETE CASCADE
 );
  
SELECT * FROM WYDPOSTPHOTO;

DROP TABLE WYDPOSTPHOTO;

