/**
 *  WYDPOST 스키마
 */

 CREATE TABLE WYDPOST (
              POSTID		NUMBER PRIMARY KEY
             ,POSTTITLE		VARCHAR2(500) NOT NULL
             ,POSTCONTENT	VARCHAR2(2000) NOT NULL
             ,POSTDATE		DATE NOT NULL
 );
  
SELECT * FROM WYDPOST;

DROP TABLE WYDPOST;
